In [2]:
import pandas as pd

## Address

In [ ]:
address = pd.read_csv("data/raw/Addresses_20260919.csv")
address.head(5)

,Street Number,Street Number Suffix,Street Name,Street Type,Street Direction,Unit Type,Unit Number,Neighbourhood,Ward,School Division,School Division Ward,Geometry,Point,Ward as of September 17,Full Address,Street Address,Plow Zone
0,82,NaN,NICHOLSON,CRES,NaN,NaN,NaN,The Maples,Old Kildonan,Seven Oaks,2,"(49.954829652213505, -97.16816354139718)",POINT (-97.16816354139718 49.954829652213505),Old Kildonan,82 NICHOLSON CRES,82 NICHOLSON CRES,J
1,73,NaN,FERNGROVE,WALK,NaN,NaN,NaN,Riverbend,North Kildonan,Seven Oaks,3,"(49.96420508265007, -97.09582484831421)",POINT (-97.09582484831421 49.96420508265007),North Kildonan,73 FERNGROVE WALK,73 FERNGROVE WALK,I
2,325,NaN,DES MEURONS,ST,NaN,NaN,NaN,Central St. Boniface,St. Boniface,Louis Riel,1,"(49.88258857021211, -97.1113540610877)",POINT (-97.1113540610877 49.88258857021211),St. Boniface,325 DES MEURONS ST,325 DES MEURONS ST,NaN
3,3,NaN,BONDAR,BAY,NaN,NaN,NaN,The Maples,Old Kildonan,Seven Oaks,2,"(49.952878301251516, -97.18350293190592)",POINT (-97.18350293190592 49.952878301251516),Old Kildonan,3 BONDAR BAY,3 BONDAR BAY,J
4,53,NaN,DESHARNAIS,ST,NaN,NaN,NaN,The Maples,Old Kildonan,Seven Oaks,2,"(49.95364446441285, -97.17808858526375)",POINT (-97.17808858526375 49.95364446441285),Old Kildonan,53 DESHARNAIS ST,53 DESHARNAIS ST,J

In [17]:
# Drop unuseful cols
cols_to_drop = [
    "Street Direction",
    "Street Number Suffix",
    "Unit Type",
    "Unit Number",
    "Point",
    "Ward as of September 17",
    "Full Address",
    "Street Address",
]

address = address.drop(columns=cols_to_drop, errors="ignore")
print(address.shape)
address.head(5)

(244037, 9)

,Street Number,Street Name,Street Type,Neighbourhood,Ward,School Division,School Division Ward,Geometry,Plow Zone
0,82,NICHOLSON,CRES,The Maples,Old Kildonan,Seven Oaks,2,"(49.954829652213505, -97.16816354139718)",J
1,73,FERNGROVE,WALK,Riverbend,North Kildonan,Seven Oaks,3,"(49.96420508265007, -97.09582484831421)",I
2,325,DES MEURONS,ST,Central St. Boniface,St. Boniface,Louis Riel,1,"(49.88258857021211, -97.1113540610877)",NaN
3,3,BONDAR,BAY,The Maples,Old Kildonan,Seven Oaks,2,"(49.952878301251516, -97.18350293190592)",J
4,53,DESHARNAIS,ST,The Maples,Old Kildonan,Seven Oaks,2,"(49.95364446441285, -97.17808858526375)",J

In [18]:
address.isna().sum()

Street Number               0
Street Name                 0
Street Type               714
Neighbourhood              10
Ward                       10
School Division           200
School Division Ward      200
Geometry                    0
Plow Zone               64776
dtype: int64

In [19]:
# Replace all missing data to None
text_columns = ["Street Type", "Neighbourhood", "Ward", "School Division", "Plow Zone"]

for col in text_columns:
    address[col] = address[col].replace({"": None, "NaN": None})

address.head(5)

,Street Number,Street Name,Street Type,Neighbourhood,Ward,School Division,School Division Ward,Geometry,Plow Zone
0,82,NICHOLSON,CRES,The Maples,Old Kildonan,Seven Oaks,2,"(49.954829652213505, -97.16816354139718)",J
1,73,FERNGROVE,WALK,Riverbend,North Kildonan,Seven Oaks,3,"(49.96420508265007, -97.09582484831421)",I
2,325,DES MEURONS,ST,Central St. Boniface,St. Boniface,Louis Riel,1,"(49.88258857021211, -97.1113540610877)",NaN
3,3,BONDAR,BAY,The Maples,Old Kildonan,Seven Oaks,2,"(49.952878301251516, -97.18350293190592)",J
4,53,DESHARNAIS,ST,The Maples,Old Kildonan,Seven Oaks,2,"(49.95364446441285, -97.17808858526375)",J

In [20]:
# Standardize column names
address.columns = [col.strip().lower().replace(" ", "_") for col in address.columns]

# Strip leading/trailing whitespaces
str_cols = address.select_dtypes(include="object").columns
for col in str_cols:
    address[col] = address[col].apply(lambda x: x.strip() if isinstance(x, str) else x)
    
address.head(5)

C:\Users\GIA DAT\AppData\Local\Temp\ipykernel_9612\499135178.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_cols = address.select_dtypes(include="object").columns

,street_number,street_name,street_type,neighbourhood,ward,school_division,school_division_ward,geometry,plow_zone
0,82,NICHOLSON,CRES,The Maples,Old Kildonan,Seven Oaks,2,"(49.954829652213505, -97.16816354139718)",J
1,73,FERNGROVE,WALK,Riverbend,North Kildonan,Seven Oaks,3,"(49.96420508265007, -97.09582484831421)",I
2,325,DES MEURONS,ST,Central St. Boniface,St. Boniface,Louis Riel,1,"(49.88258857021211, -97.1113540610877)",NaN
3,3,BONDAR,BAY,The Maples,Old Kildonan,Seven Oaks,2,"(49.952878301251516, -97.18350293190592)",J
4,53,DESHARNAIS,ST,The Maples,Old Kildonan,Seven Oaks,2,"(49.95364446441285, -97.17808858526375)",J

In [21]:
# Extract latitude and longitude
geo_split = address["geometry"].str.extract(r"\((?P<latitude>[^,]+),\s*(?P<longitude>[^)]+)\)")

# Convert to float
address["latitude"] = pd.to_numeric(geo_split["latitude"], errors="coerce")
address["longitude"] = pd.to_numeric(geo_split["longitude"], errors="coerce")

# Drop geometry col
address = address.drop(columns=["geometry"])
address.head(5)

,street_number,street_name,street_type,neighbourhood,ward,school_division,school_division_ward,plow_zone,latitude,longitude
0,82,NICHOLSON,CRES,The Maples,Old Kildonan,Seven Oaks,2,J,49.954830,-97.168164
1,73,FERNGROVE,WALK,Riverbend,North Kildonan,Seven Oaks,3,I,49.964205,-97.095825
2,325,DES MEURONS,ST,Central St. Boniface,St. Boniface,Louis Riel,1,NaN,49.882589,-97.111354
3,3,BONDAR,BAY,The Maples,Old Kildonan,Seven Oaks,2,J,49.952878,-97.183503
4,53,DESHARNAIS,ST,The Maples,Old Kildonan,Seven Oaks,2,J,49.953644,-97.178089

In [23]:
# Check duplication
address.duplicated().sum()

np.int64(0)

In [25]:
address.dtypes

street_number             int64
street_name                 str
street_type                 str
neighbourhood               str
ward                        str
school_division             str
school_division_ward        str
plow_zone                   str
latitude                float64
longitude               float64
dtype: object

In [26]:
address.info()

<class 'pandas.DataFrame'>
RangeIndex: 244037 entries, 0 to 244036
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   street_number         244037 non-null  int64
 1   street_name           244037 non-null  str
 2   street_type           243323 non-null  str
 3   neighbourhood         244027 non-null  str
 4   ward                  244027 non-null  str
 5   school_division       243837 non-null  str
 6   school_division_ward  243837 non-null  str
 7   plow_zone             179261 non-null  str
 8   latitude              244037 non-null  float64
 9   longitude             244037 non-null  float64
dtypes: float64(2), int64(1), str(7)
memory usage: 18.6 MB

In [27]:
address.to_csv("data/cleaned/cleaned_addresses.csv", index=False)
print("Done")

Done

## Road Segment

In [35]:
road_segment = pd.read_csv("data/raw/City_of_Winnipeg_LRS_20260919.csv")
road_segment.head(5)

,Street Name,Street Qualifier,Begin Measure,End Measure,Location
0,01 Service Rd,A,0,46.14112,MULTILINESTRING ((-97.12746772852147 49.758697...
1,2nd St,A,0,523.98429,MULTILINESTRING ((-96.9595792160331 49.8820272...
2,Abbeydale Cres,A,0,69.10982,MULTILINESTRING ((-97.1786707194553 49.8100994...
3,Abbeydale Cres,A,69.10982,86.23298,MULTILINESTRING ((-97.17911889309687 49.810649...
4,Abbeydale Cres,A,86.23298,441.16906,MULTILINESTRING ((-97.17922993433433 49.810785...

In [36]:
road_segment.info()

<class 'pandas.DataFrame'>
RangeIndex: 32086 entries, 0 to 32085
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Street Name       32086 non-null  str
 1   Street Qualifier  32086 non-null  str
 2   Begin Measure     32086 non-null  str
 3   End Measure       32086 non-null  str
 4   Location          32086 non-null  str
dtypes: str(5)
memory usage: 1.2 MB

In [37]:
road_segment.shape

(32086, 5)

In [38]:
road_segment.isna().sum()

Street Name         0
Street Qualifier    0
Begin Measure       0
End Measure         0
Location            0
dtype: int64

In [ ]:
# Standardize column name
road_segment.columns = [col.strip().lower().replace(" ", "_") for col in road_segment.columns]

# Strip whitespaces
str_cols = ["street_name", "street_qualifier", "location"]
for col in str_cols:
    road_segment[col] = road_segment[col].astype(str).str.strip()

road_segment.head(5)

,street_name,street_qualifier,begin_measure,end_measure,location
0,01 Service Rd,A,0,46.14112,MULTILINESTRING ((-97.12746772852147 49.758697...
1,2nd St,A,0,523.98429,MULTILINESTRING ((-96.9595792160331 49.8820272...
2,Abbeydale Cres,A,0,69.10982,MULTILINESTRING ((-97.1786707194553 49.8100994...
3,Abbeydale Cres,A,69.10982,86.23298,MULTILINESTRING ((-97.17911889309687 49.810649...
4,Abbeydale Cres,A,86.23298,441.16906,MULTILINESTRING ((-97.17922993433433 49.810785...

In [33]:
road_segment.info()

<class 'pandas.DataFrame'>
RangeIndex: 32086 entries, 0 to 32085
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   street_name       32086 non-null  str
 1   street_qualifier  32086 non-null  str
 2   begin_measure     22189 non-null  float64
 3   end_measure       21248 non-null  float64
 4   location          32086 non-null  str
dtypes: float64(2), str(3)
memory usage: 1.2 MB

In [40]:
## Remove "," in begin measure, end measure
road_segment["begin_measure"] = (
    road_segment["begin_measure"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)
road_segment["end_measure"] = (
    road_segment["end_measure"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.strip()
)

## Convert to float
road_segment["begin_measure"] = pd.to_numeric(road_segment["begin_measure"], errors="coerce")
road_segment["end_measure"] = pd.to_numeric(road_segment["end_measure"], errors="coerce")

road_segment.isna().sum()

street_name         0
street_qualifier    0
begin_measure       0
end_measure         0
location            0
dtype: int64

In [41]:
road_segment.sample(5)

,street_name,street_qualifier,begin_measure,end_measure,location
23121,River Ridge Pl,A,247.08292,309.76433,MULTILINESTRING ((-97.08627793891704 49.953593...
26999,Sterling Lyon Pky,B,2508.57065,2732.86096,MULTILINESTRING ((-97.2192244354326 49.8422132...
15919,Margaret Ave,A,621.93555,829.74897,MULTILINESTRING ((-97.1177514258926 49.9492700...
16266,Mazenod Rd,B,0.00000,13.94094,MULTILINESTRING ((-97.0494990367071 49.8859213...
31997,York Ave,A,263.04732,364.43987,MULTILINESTRING ((-97.13580309685872 49.890367...

In [42]:
road_segment.info()

<class 'pandas.DataFrame'>
RangeIndex: 32086 entries, 0 to 32085
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   street_name       32086 non-null  str
 1   street_qualifier  32086 non-null  str
 2   begin_measure     32086 non-null  float64
 3   end_measure       32086 non-null  float64
 4   location          32086 non-null  str
dtypes: float64(2), str(3)
memory usage: 1.2 MB

In [43]:
road_segment.duplicated().sum()

np.int64(0)

In [44]:
road_segment.to_csv("data/cleaned/cleaned_road_segment.csv", index=False)
print("Done")

Done

## Road Block

In [45]:
road_block = pd.read_csv("data/raw/LRS_Block_Segments_20260919.csv")
road_block.head(5)

,ID,Street Name,Street Qualifier,Begin Measure,End Measure,Block ID,Street Qualfiier Secondary,Address From Left,Address To Left,Address From Right,Address To Right,Number of Lanes,Street Class,Street Type Secondary,Oneway,Location
0,1,Pentland St,A,200.94417924943,275.29982060422,75,NaN,NaN,NaN,NaN,NaN,2.0,Local,Street,0.0,LINESTRING (-97.07634414033403 49.948815375889...
1,2,Edkar Cres,A,248.89192717786,341.40791788907,76,NaN,NaN,NaN,NaN,NaN,2.0,Local,Street,0.0,LINESTRING (-97.07480566694106 49.951724217501...
2,3,Fortier Ave,A,342.66947655659,461.09709078907,77,NaN,NaN,NaN,NaN,NaN,2.0,Local,Street,0.0,LINESTRING (-97.07515399709614 49.949930797940...
3,4,Kellas St,A,0,80.55455248334,78,NaN,NaN,NaN,NaN,NaN,2.0,Local,Street,0.0,LINESTRING (-97.07363523875628 49.946964585760...
4,6,Murray Ave,A,"2,815.6113663144","2,836.55306863056",81,NaN,NaN,NaN,NaN,NaN,2.0,Arterial,Street,0.0,LINESTRING (-97.13140941601733 49.968774251855...

In [46]:
# Drop unuseful cols
cols_to_drop = [
    "ID",
    "Block ID",
    "Street Qualfiier Secondary",
    "Address From Left",
    "Address To Left",
    "Address From Right",
    "Address To Right",
]

road_block = road_block.drop(columns=cols_to_drop, errors="ignore")
print(road_block.shape)
road_block.sample(5)

(24359, 9)

,Street Name,Street Qualifier,Begin Measure,End Measure,Number of Lanes,Street Class,Street Type Secondary,Oneway,Location
3892,St Mary's Rd,B,"2,562.50813401891","2,657.55883974821",2.0,Arterial,Street,1.0,LINESTRING (-97.11198100164893 49.855345844978...
13000,River Rd,A,"2,049.8013139637","2,078.25883639872",2.0,Arterial,Street,0.0,LINESTRING (-97.13721464475768 49.821535453529...
22549,Inkster Blvd,B,"1,808.9845956841","1,847.31673578713",2.0,Arterial,Railway Crossing,1.0,LINESTRING (-97.14658779415086 49.934592962666...
14654,Lindenwood Dr E,Service Road_20869,0,255.49555836361,2.0,Local,Street,0.0,LINESTRING (-97.18313495723869 49.836376469909...
9114,Beaverhill Blvd,A,"1,990.3721715729","2,078.71282337789",2.0,Collector,Street,0.0,LINESTRING (-97.06464196663887 49.849377733237...

In [47]:
road_block.isna().sum()

Street Name                0
Street Qualifier           0
Begin Measure              0
End Measure                0
Number of Lanes           47
Street Class              25
Street Type Secondary    102
Oneway                   173
Location                   0
dtype: int64

In [48]:
road_block.info()

<class 'pandas.DataFrame'>
RangeIndex: 24359 entries, 0 to 24358
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Street Name            24359 non-null  str
 1   Street Qualifier       24359 non-null  str
 2   Begin Measure          24359 non-null  str
 3   End Measure            24359 non-null  str
 4   Number of Lanes        24312 non-null  float64
 5   Street Class           24334 non-null  str
 6   Street Type Secondary  24257 non-null  str
 7   Oneway                 24186 non-null  float64
 8   Location               24359 non-null  str
dtypes: float64(2), str(7)
memory usage: 1.7 MB

In [49]:
# Standardize column names
road_block.columns = [col.strip().lower().replace(" ", "_") for col in road_block.columns]

# Strip whitespaces
str_cols = ["street_name", "street_qualifier", "street_class", "street_type_secondary", "location"]
for col in str_cols:
    road_block[col] = road_block[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Clean comma and convert measures to float
for measure_col in ["begin_measure", "end_measure"]:
    road_block[measure_col] = (
        road_block[measure_col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    road_block[measure_col] = pd.to_numeric(road_block[measure_col], errors="coerce")

# Cast lanes and oneway to int
road_block["number_of_lanes"] = road_block["number_of_lanes"].astype("Int64")
road_block["oneway"] = road_block["oneway"].astype("Int64")

road_block.info()

<class 'pandas.DataFrame'>
RangeIndex: 24359 entries, 0 to 24358
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   street_name            24359 non-null  str
 1   street_qualifier       24359 non-null  str
 2   begin_measure          24359 non-null  float64
 3   end_measure            24359 non-null  float64
 4   number_of_lanes        24312 non-null  Int64
 5   street_class           24334 non-null  str
 6   street_type_secondary  24257 non-null  str
 7   oneway                 24186 non-null  Int64
 8   location               24359 non-null  str
dtypes: Int64(2), float64(2), str(5)
memory usage: 1.7 MB

In [50]:
road_block.sample(5)

,street_name,street_qualifier,begin_measure,end_measure,number_of_lanes,street_class,street_type_secondary,oneway,location
16099,St Anne's Rd,B,1121.864526,1141.485068,2,Arterial,Street,1,LINESTRING (-97.10388866926377 49.855400746301...
15826,Oak Point Hwy,Cut Through_3957,0.000000,24.844376,2,Arterial,Street,0,LINESTRING (-97.22056167776435 49.935382749092...
23467,Ravelston Ave W,A,1685.089134,1869.056550,2,Collector,Street,0,LINESTRING (-97.02598682087527 49.897636627036...
16760,Norquay St,A,0.000000,133.777672,2,Local,Street,0,LINESTRING (-97.14853379715635 49.878448133534...
17111,Waverley St,A,4071.081503,4635.931729,2,Arterial,Street,2,LINESTRING (-97.17969033951657 49.838669475944...

In [51]:
road_block.duplicated().sum()

np.int64(0)

In [52]:
road_block.to_csv("data/cleaned/cleaned_road_block.csv", index=False)
print("Done")

Done

## Neighborhoods

In [53]:
neighborhood = pd.read_csv("data/raw/Neighbourhoods_20260919.csv")
neighborhood.sample(5)

,ID,Name,Location
218,59,Grant Park,MULTIPOLYGON (((-97.1524311168724 49.854180389...
36,143,Pacific Industrial,MULTIPOLYGON (((-97.17143556734793 49.90530612...
236,88,South Portage,MULTIPOLYGON (((-97.15086574062387 49.89093332...
235,87,Glendale,MULTIPOLYGON (((-97.3264658167135 49.878360882...
59,178,Parker,MULTIPOLYGON (((-97.17615035641555 49.85053788...

In [54]:
neighborhood = neighborhood.drop(columns="ID", errors="ignore")
print(neighborhood.shape)
neighborhood.sample(5)

(237, 2)

                      Name                                           Location
114               Elm Park  MULTIPOLYGON (((-97.11277638365297 49.86613419...
154  Central River Heights  MULTIPOLYGON (((-97.17494371135584 49.86300992...
168                 Peguis  MULTIPOLYGON (((-97.05677171343187 49.91057969...
182                  Vista  MULTIPOLYGON (((-97.1140115902755 49.823846094...
148              Robertson  MULTIPOLYGON (((-97.15916472134121 49.94023011...

In [56]:
neighborhood.info()

<class 'pandas.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      237 non-null    str
 1   Location  237 non-null    str
dtypes: str(2)
memory usage: 3.8 KB

In [67]:
neighborhood.isna().sum()

name        0
location    0
dtype: int64

In [57]:
# Standardize column names
neighborhood.columns = [col.strip().lower().replace(" ", "_") for col in neighborhood.columns]

# Strip whitespaces
str_cols = ["name", "location"]
for col in str_cols:
    neighborhood[col] = neighborhood[col].astype(str).str.strip()
    
neighborhood.info()

<class 'pandas.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      237 non-null    str
 1   location  237 non-null    str
dtypes: str(2)
memory usage: 3.8 KB

In [58]:
neighborhood.sample(5)

              name                                           location
47   Fort Richmond  MULTIPOLYGON (((-97.11787382379941 49.79345443...
155       Montcalm  MULTIPOLYGON (((-97.1570906560849 49.801422442...
200    Munroe West  MULTIPOLYGON (((-97.10402032552093 49.92758002...
187         Regent  MULTIPOLYGON (((-97.06895236112479 49.89834490...
89   Kil-Cona Park  MULTIPOLYGON (((-97.02359266786286 49.94195867...

In [59]:
neighborhood.duplicated().sum()

np.int64(0)

In [60]:
neighborhood.to_csv("data/cleaned/cleaned_neighborhood.csv", index=False)
print("Done")

Done

## Plow Zone

In [3]:
plow_zone = pd.read_csv("data/raw/Plow_Zones_20260919.csv")
plow_zone.sample(5)

,Entity ID,City Area,Plow Zone,the_geom
75,95,South,G,MULTIPOLYGON (((-97.15257157883838 49.85385034...
62,60,East,X,MULTIPOLYGON (((-96.96804982262822 49.89334369...
71,75,East,X,MULTIPOLYGON (((-97.07591806717906 49.81957903...
59,67,East,C,MULTIPOLYGON (((-97.11160218866007 49.85251460...
25,21,East,D,MULTIPOLYGON (((-97.10826365501386 49.92952442...

In [4]:
plow_zone = plow_zone.drop(columns="City Area", errors="ignore")
print(plow_zone.shape)

(82, 3)

In [5]:
plow_zone.sample(5)

   Entity ID Plow Zone                                           the_geom
47        40         Q  MULTIPOLYGON (((-97.21801249884182 49.91200429...
29        25         P  MULTIPOLYGON (((-97.26307280656908 49.87194753...
32       120         G  MULTIPOLYGON (((-97.16243362759977 49.87850545...
63        61         X  MULTIPOLYGON (((-97.09965146295663 49.90171578...
50        45         A  MULTIPOLYGON (((-96.9976575040497 49.899754592...

In [6]:
plow_zone.isna().sum()

Entity ID    0
Plow Zone    0
the_geom     0
dtype: int64

In [7]:
plow_zone.info()

<class 'pandas.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Entity ID  82 non-null     str
 1   Plow Zone  82 non-null     str
 2   the_geom   82 non-null     str
dtypes: str(3)
memory usage: 2.1 KB

In [8]:
# rename the_geom to location for consistency
plow_zone = plow_zone.rename(columns={"the_geom": "location"})

# Standardize column names
plow_zone.columns = [col.strip().lower().replace(" ", "_") for col in plow_zone.columns]

# Strip whitespaces
str_cols = ["plow_zone", "location"]
for col in str_cols:
    plow_zone[col] = plow_zone[col].astype(str).str.strip()

In [9]:
plow_zone.duplicated().sum()

np.int64(0)

In [10]:
plow_zone.sample(5)

   entity_id plow_zone                                           location
38        37         B  MULTIPOLYGON (((-97.13952869619217 49.89648363...
68        71         C  MULTIPOLYGON (((-97.18025843551388 49.83340651...
64        62         O  MULTIPOLYGON (((-97.22990645835317 49.86691159...
57     5,432         C  MULTIPOLYGON (((-97.19384739529076 49.81098500...
81       128         I  MULTIPOLYGON (((-97.20219170785724 49.96059953...

In [11]:
plow_zone.to_csv("data/cleaned/cleaned_plow_zone.csv", index=False)
print("Done")

Done

## School Division

In [73]:
school_division = pd.read_csv("data/raw/School_Divsions_20260919.csv")
school_division.sample(5)

,Name,the_geom,Website,Division
0,Seine River,MULTIPOLYGON (((-97.18790394575838 49.76817920...,http://www.srsd.mb.ca,14
7,River East - Transcona,MULTIPOLYGON (((-97.01377580733107 49.91585165...,http://www.retsd.mb.ca,72
5,Winnipeg,MULTIPOLYGON (((-97.19510696581712 49.92383220...,https://www.winnipegsd.ca,1
6,Pembina Trails,MULTIPOLYGON (((-97.29269491974017 49.86384474...,http://www.pembinatrails.ca,7
3,St James-Assiniboia,MULTIPOLYGON (((-97.22986786066896 49.91659185...,http://www.sjsd.net,2

In [75]:
school_division = school_division.drop(columns="Division", errors="ignore")
print(school_division.shape)
school_division.info()

(8, 3)
<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      8 non-null      str
 1   the_geom  8 non-null      str
 2   Website   8 non-null      str
dtypes: str(3)
memory usage: 324.0 bytes

In [76]:
# rename the_geom to location for consistency
school_division = school_division.rename(columns={"the_geom": "location"})

# Standardize column names
school_division.columns = [col.strip().lower().replace(" ", "_") for col in school_division.columns]

# Strip whitespaces
str_cols = ["name", "location", "website"]
for col in str_cols:
    school_division[col] = school_division[col].astype(str).str.strip()

In [77]:
school_division.duplicated().sum()

np.int64(0)

In [78]:
school_division.sample(5)

,name,location,website
0,Seine River,MULTIPOLYGON (((-97.18790394575838 49.76817920...,http://www.srsd.mb.ca
4,Interlake,MULTIPOLYGON (((-97.29446929542303 49.93132595...,http://www.isd21.mb.ca
7,River East - Transcona,MULTIPOLYGON (((-97.01377580733107 49.91585165...,http://www.retsd.mb.ca
5,Winnipeg,MULTIPOLYGON (((-97.19510696581712 49.92383220...,https://www.winnipegsd.ca
2,Seven Oaks,MULTIPOLYGON (((-97.1137921542198 49.978127897...,http://www.7oaks.org

In [79]:
school_division.to_csv("data/cleaned/cleaned_school_division.csv", index=False)
print("Done")

Done

## Speed Limit

In [81]:
speed_limit = pd.read_csv("data/raw/LRS_Speed_Limits_20260919.csv")
speed_limit.sample(5)

,ID,Street Name,Street Qualifier,Begin Measure,End Measure,Speed Limit,Speed Limit Description,Speed Limit Jurisdiction,Location
4283,8728,Mapleton Dr,A,0,706.62885,50.0,Speed Limits are less than or equal to 50 kph,City Transportation,MULTILINESTRING ((-97.1733454087958 49.9471276...
3253,4566,Inniscross Pl,A,0,57.25014,50.0,Speed Limits are less than or equal to 50 kph,City Transportation,MULTILINESTRING ((-97.2101144525282 49.8157723...
5784,8593,Ragsdill Rd,A,0,"1,151.82827",50.0,Speed Limits are less than or equal to 50 kph,City Transportation,MULTILINESTRING ((-97.05136236161383 49.944559...
7359,5254,Vista Ave,Right Turn_22461,0,44.34321,50.0,Speed Limits are less than or equal to 50 kph,City Transportation,MULTILINESTRING ((-97.11324679309645 49.820547...
1981,7759,Dublin Ave,B,0,113.07622,60.0,Posted 60 kph speed limit,City Transportation,MULTILINESTRING ((-97.18934695931779 49.910975...

In [82]:
speed_limit = speed_limit.drop(columns=["ID", "Speed Limit Description", "Speed Limit Jurisdiction"], errors="ignore")
print(speed_limit.shape)
speed_limit.info()

(7884, 6)
<class 'pandas.DataFrame'>
RangeIndex: 7884 entries, 0 to 7883
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Street Name       7884 non-null   str
 1   Street Qualifier  7884 non-null   str
 2   Begin Measure     7884 non-null   str
 3   End Measure       7884 non-null   str
 4   Speed Limit       7449 non-null   float64
 5   Location          7884 non-null   str
dtypes: float64(1), str(5)
memory usage: 369.7 KB

In [83]:
#Standardize column names
speed_limit.columns = [col.strip().lower().replace(" ", "_") for col in speed_limit.columns]

# Strip whitespaces
str_cols = ["street_name", "street_qualifier", "location"]
for col in str_cols:
    speed_limit[col] = speed_limit[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Clean comma and convert measures to float
for measure_col in ["begin_measure", "end_measure"]:
    speed_limit[measure_col] = (
        speed_limit[measure_col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    speed_limit[measure_col] = pd.to_numeric(speed_limit[measure_col], errors="coerce")

# Cast speed_limit to int
speed_limit["speed_limit"] = speed_limit["speed_limit"].astype("Int64")

In [84]:
speed_limit.duplicated().sum()

np.int64(0)

In [88]:
speed_limit.sample(5)

,street_name,street_qualifier,begin_measure,end_measure,speed_limit,location
2478,Formal Garden Way,C,0.00000,319.49721,30,MULTILINESTRING ((-97.22124603530519 49.867566...
4394,Maynard Close,A,0.00000,428.29518,50,MULTILINESTRING ((-97.16183040172146 49.947439...
6797,St Thomas Rd,A,402.80496,670.25775,50,MULTILINESTRING ((-97.10760188922238 49.853652...
266,Argue St,A,394.99952,715.67518,50,MULTILINESTRING ((-97.14788482615211 49.855872...
4193,Main St,A,216.70000,3184.50000,50,MULTILINESTRING ((-97.13445294915152 49.887798...

In [89]:
speed_limit.to_csv("data/cleaned/cleaned_speed_limit.csv", index=False)
print("Done")

Done

## School Zone

In [14]:
school_zone = pd.read_csv("data/raw/LRS_School_Speed_Limits_20260919.csv")
school_zone.sample(5)

,ID,Street Name,Street Qualifier,Begin Measure,End Measure,School,Speed Limit,Effective Days,Effective Time,Legislation Link,Location
118,126,Minnetonka St,A,608.82469,828.86017,Minnetonka School,30,Mon-Fri June-Sept,07:00-17:30,http://clkapps.winnipeg.ca/dmis/docext/viewdoc...,LINESTRING (-97.12326777819413 49.820149753467...
240,256,Beaumont St,A,414.96485,715.97833,General Byng School,30,Mon-Fri June-Sept,07:00-17:30,http://clkapps.winnipeg.ca/dmis/docext/viewdoc...,LINESTRING (-97.16126596796384 49.844752203737...
241,257,Shamrock Dr,A,23.80604,324.97564,Shamrock School,30,Mon-Fri June-Sept,07:00-17:30,http://clkapps.winnipeg.ca/dmis/docext/viewdoc...,LINESTRING (-97.06386747425968 49.845777106419...
87,94,Church Ave,A,364.3586,553.69482,Champlain School,30,Mon-Fri June-Sept,07:00-17:30,http://clkapps.winnipeg.ca/dmis/docext/viewdoc...,LINESTRING (-97.12937651934325 49.922803047164...
431,453,Oddy St,A,445,564.03021,Brooklands School,30,Mon-Fri June-Sept,07:00-17:30,http://clkapps.winnipeg.ca/dmis/docext/viewdoc...,LINESTRING (-97.20262738540602 49.920982397707...

In [15]:
school_zone = school_zone.drop(columns=["ID", "Legislation Link"], errors="ignore")
print(school_zone.shape)
school_zone.info()

(438, 9)
<class 'pandas.DataFrame'>
RangeIndex: 438 entries, 0 to 437
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Street Name       438 non-null    str
 1   Street Qualifier  438 non-null    str
 2   Begin Measure     438 non-null    str
 3   End Measure       438 non-null    str
 4   School            438 non-null    str
 5   Speed Limit       438 non-null    int64
 6   Effective Days    438 non-null    str
 7   Effective Time    438 non-null    str
 8   Location          438 non-null    str
dtypes: int64(1), str(8)
memory usage: 30.9 KB

In [16]:
# Standardize column names
school_zone.columns = [col.strip().lower().replace(" ", "_") for col in school_zone.columns]

# Strip whitespaces
str_cols = school_zone.select_dtypes(include="str").columns
for col in str_cols:
    school_zone[col] = school_zone[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

# Clean commas and convert measures to float
for measure_col in ["begin_measure", "end_measure"]:
    school_zone[measure_col] = (
        school_zone[measure_col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    school_zone[measure_col] = pd.to_numeric(school_zone[measure_col], errors="coerce")

# Convert speed_limit to int
school_zone["speed_limit"] = pd.to_numeric(school_zone["speed_limit"], errors="coerce").astype("Int64")

In [17]:
school_zone.duplicated().sum()

np.int64(0)

In [18]:
school_zone.sample(5)

,street_name,street_qualifier,begin_measure,end_measure,school,speed_limit,effective_days,effective_time,location
422,Birchdale Ave,A,21.60000,532.70000,Nordale School,30,Mon-Fri June-Sept,07:00-17:30,LINESTRING (-97.13035263333926 49.871502879351...
404,Keslar Rd,A,133.70000,497.60000,Richmond Montessori School,30,Mon-Fri June-Sept,07:00-17:30,LINESTRING (-97.1674752730066 49.7924329333000...
109,Point Rd,A,553.79799,766.03551,Ecole Viscount Alexander,30,Mon-Fri June-Sept,07:00-17:30,LINESTRING (-97.14349419764244 49.846660149650...
173,Pacific Ave,A,1926.56648,2182.48033,Pinkham School,30,Mon-Fri June-Sept,07:00-17:30,LINESTRING (-97.15631492241364 49.907338532050...
283,Bournais Dr,A,238.90818,569.88793,Bernie Wolfe Community School,30,Mon-Fri June-Sept,07:00-17:30,LINESTRING (-97.04147683056657 49.891566278428...

In [19]:
school_zone.to_csv("data/cleaned/cleaned_school_zone.csv", index=False)
print("Done")

Done